{{- $ca := genCA "osiris-proxy-injector-ca" 3650 }}
{{- $cn := printf "%s-proxy-injector" (include "osiris.fullname" .) }}
{{- $altName1 := printf "%s-proxy-injector.%s" (include "osiris.fullname" .) .Release.Namespace }}
{{- $altName2 := printf "%s-proxy-injector.%s.svc" (include "osiris.fullname" .) .Release.Namespace }}
{{- $altName3 := printf "%s-proxy-injector.%s.svc.cluster" (include "osiris.fullname" .) .Release.Namespace }}
{{- $altName4 := printf "%s-proxy-injector.%s.svc.cluster.local" (include "osiris.fullname" .) .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $altName1 $altName2 $altName3 $altName4) 3650 $ca }}

{{- if not (.Values.certmanager.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osiris.fullname" . }}-proxy-injector-cert
  labels:
    app.kubernetes.io/name: {{ include "osiris.name" . }}-proxy-injector
    helm.sh/chart: {{ include "osiris.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
{{- end }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "osiris.fullname" . }}-proxy-injector
  labels:
    app.kubernetes.io/name: {{ include "osiris.name" . }}-proxy-injector
    helm.sh/chart: {{ include "osiris.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
  {{- if .Values.certmanager.enabled }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "osiris.fullname" . }}-proxy-injector-cert
  {{- end }}
webhooks:
- name: proxy-injector.osiris.dm.gg
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "osiris.fullname" . }}-proxy-injector
      path: "/mutate"
    {{- if not (.Values.certmanager.enabled) }}
    caBundle: {{ b64enc $ca.Cert }}
    {{- end }}
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    resources:
    - pods
    operations:
    - CREATE
  failurePolicy: Ignore
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
